### ISSUE TITLE
Problem of multi-GPU "'NCCL' has no attribute 'new_uid'"

### ISSUE THREAD

**Issue by mysayalHan** [bharatsingh430/py-R-FCN-multiGPU#21]
Hi, I had clone your code and install NCCL. However , when run the file train_multi_gpu.py, I encounter a error:

> Traceback (most recent call last):
  File "./tools/train_net_multi_gpu.py", line 109, in <module>
    max_iter=args.max_iters, gpus=gpus)
  File "/home/ultron/py-R-FCN-multiGPU/tools/../lib/fast_rcnn/train_multi_gpu.py", line 205, in train_net_multi_gpu
    uid = caffe.NCCL.new_uid()
AttributeError: type object 'NCCL' has no attribute 'new_uid'

I think I installed NCCL correctly, and I found the same problem in the issue, but it did not work

**Comment by mysayalHan** [comment]
OK. I solve this problem.
I use cmake to build caffe. However, in cmake configuration, it shows Found NCCL, so I ignore USE_NCCL OFF. So, if you use cmake, you should change USE_NCCL from ON to OFF in CMakeLists.txt.
